pnpm publish --filter ./packages/colors
pnpm publish --filter ./packages/numbers
pnpm publish --filter ./packages/commons
pnpm publish --filter ./packages/checkers
pnpm publish --filter ./packages/collections
pnpm publish --filter ./packages/encoding
pnpm publish --filter ./packages/iter
pnpm publish --filter ./packages/memoize
pnpm publish --filter ./packages/objects
pnpm publish --filter ./packages/pretty-console
pnpm publish --filter ./packages/promises
pnpm publish --filter ./packages/strings
pnpm publish --filter ./packages/url
pnpm publish --filter ./packages/index
