pnpm publish --filter farrapa-colors
pnpm publish --filter farrapa-numbers
pnpm publish --filter farrapa-checkers
pnpm publish --filter farrapa-collections
pnpm publish --filter farrapa-encoding
pnpm publish --filter farrapa-iter
pnpm publish --filter farrapa-memoize
pnpm publish --filter farrapa-objects
pnpm publish --filter farrapa-pretty-console
pnpm publish --filter farrapa-promises
pnpm publish --filter farrapa-strings
pnpm publish --filter farrapa-url